project:
  type: book

book:
  title: R in Production
  author: Hadley Wickham

  reader-mode: true

  site-url: https://r-in-production.org/
  repo-url: https://github.com/hadley/r-in-production/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - introduction.qmd
    - whole-game.qmd
    - project-life.qmd

    - part: production-code.qmd
      chapters:
        - another-machine.qmd
        - right-tool.qmd
        - auth.qmd
        - optimize.qmd
        - logging.qmd
        - debugging.qmd

    - part: getting-to-production.qmd
      chapters:
      - paper-cuts.qmd
      - github-actions.qmd
      - packages.qmd
        
    - part: multiple-times.qmd
      chapters:
        - run-repeatedly.qmd
        - schema.qmd
        - packages-platform.qmd
        - universe.qmd
        - requirements.qmd

    - part: data.qmd
      chapters: 
        - access-data.qmd
        - manage-credentials.qmd
        - integrate.qmd

    - part: packages-envs.qmd
      chapters: 
        - pkg-best-practices.qmd
        - reproducibility.qmd
        - it-sec-collab.qmd

    - part: security.qmd
      chapters: 
        - security-code.qmd
        - security-pkgs.qmd
        - security-deployment.qmd
        - security-event.qmd

    - part: operations.qmd
      chapters:
        - version-control.qmd
        - cicd.qmd
        - shipdontsink.qmd
        - careandfeeding.qmd

    - where-to-run.qmd

    - part: shared-responsibility.qmd
      chapters:
      - team-conventions.qmd
      - internal-packages.qmd
      - parquet.qmd
      - work-with-it.qmd
      - metric.qmd

format:
  html:
    theme:
      - cosmo
      - r-in-production.scss
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple
